services:
  api-gateway:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      # Password__File is not supported, so use .env instead to inject password
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${CERTS_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: /run/secrets/dev-certs

  server:
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      # Password__File is not supported, so use .env instead to inject password
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${CERTS_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: /run/secrets/dev-certs
      ConnectionStrings__RecipesDb: "Host=db;Port=5432;Username=postgres;Password=${DB_PASSWORD};Database=recipes-db"
    secrets:
      - dev-certs

  db:
    image: postgres:16.4-alpine
    shm_size: 128mb
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      # Password__FILE is supported by postgres, but again not in dotnet, so .env file again
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - PGUSER=${DB_USER}
    networks:
      - backend

secrets:
  dev-certs:
    file: secrets/aspnetapp.pfx

volumes:
  db_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'db-data/data'
