services:
  server:
    depends_on:
      db:
        condition: service_healthy
    environment:
      ConnectionStrings__RecipesDb: "Host=db;Port=5432;Username=postgres;Password=${DB_PASSWORD};Database=recipes-db"

  db:
    image: postgres:16.4-alpine
    shm_size: 128mb
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      # Password__FILE is supported by postgres, but again not in dotnet, so .env file again
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - PGUSER=${DB_USER}
    networks:
      - backend

volumes:
  db_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'db-data/data'
