name: whojoo-site

services:
  api-gateway:
    ports:
      - "5001:80"
    environment:
      ReverseProxy:Clusters:webCluster:Destinations:destination1:Address: http://web:80
      ReverseProxy:Clusters:backendCluster:Destinations:destination1:Address: http://server-1:80
      ReverseProxy:Clusters:backendCluster:Destinations:destination2:Address: http://server-2:80
      ReverseProxy:Clusters:backendCluster:Destinations:destination3:Address: http://server-3:80
    networks:
      - frontend
      - backend
    secrets:
      - dev-certs

  web:
    networks:
      - frontend

  server-1:
    hostname: server-1
    networks:
      - backend

  server-2:
    hostname: server-2
    networks:
      - backend

  server-3:
    hostname: server-3
    networks:
      - backend

networks:
  frontend:
  backend:
