name: whojoo-site

services:
  api-gateway:
    image: whojoo-site/api-gateway:${API_GATEWAY_VERSION}
    ports:
      - "5001:80"
    environment:
      ReverseProxy:Clusters:webCluster:Destinations:destination1:Address: http://web:80
      ReverseProxy:Clusters:backendCluster:Destinations:destination1:Address: http://server:80
    networks:
      - frontend
      - backend
    secrets:
      - dev-certs

#  web:
#    image: whojoo-site/web:${WEB_VERSION}
#    networks:
#      - frontend
#    depends_on:
#      consul:
#        condition: service_started

  server:
    image: whojoo-site/server:${SERVER_VERSION}
    networks:
      - backend

networks:
  frontend:
  backend:
