name: whojoo-site

services:
  api-gateway:
    build: 
      context: .
      dockerfile: api-gateway.Dockerfile
    ports:
      - 5001:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      # Password__File is not supported, so use .env instead to inject password
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${CERTS_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: /run/secrets/dev-certs
      ReverseProxy:Clusters:webCluster:Destinations:destination1:Address: http://web:4000
      ReverseProxy:Clusters:backendCluster:Destinations:destination1:Address: http://server:80
    networks:
      - frontend
      - backend
    secrets:
      - dev-certs

  web:
    build: 
      context: .
      dockerfile: web.Dockerfile
    networks:
      - frontend

  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - 5002:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      # Password__File is not supported, so use .env instead to inject password
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${CERTS_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: /run/secrets/dev-certs
    networks:
      - backend
    secrets:
      - dev-certs

secrets:
  dev-certs:
    file: secrets/aspnetapp.pfx

networks:
  frontend:
  backend: