// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace WhojooSite.View.Clients.RecipesModule.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListCompleteRecipesResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The recipes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::WhojooSite.View.Clients.RecipesModule.Models.Recipe>? Recipes { get; set; }
#nullable restore
#else
        public List<global::WhojooSite.View.Clients.RecipesModule.Models.Recipe> Recipes { get; set; }
#endif
        /// <summary>The totalCount property</summary>
        public int? TotalCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::WhojooSite.View.Clients.RecipesModule.Models.ListCompleteRecipesResponse"/> and sets the default values.
        /// </summary>
        public ListCompleteRecipesResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::WhojooSite.View.Clients.RecipesModule.Models.ListCompleteRecipesResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::WhojooSite.View.Clients.RecipesModule.Models.ListCompleteRecipesResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::WhojooSite.View.Clients.RecipesModule.Models.ListCompleteRecipesResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "recipes", n => { Recipes = n.GetCollectionOfObjectValues<global::WhojooSite.View.Clients.RecipesModule.Models.Recipe>(global::WhojooSite.View.Clients.RecipesModule.Models.Recipe.CreateFromDiscriminatorValue)?.AsList(); } },
                { "totalCount", n => { TotalCount = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::WhojooSite.View.Clients.RecipesModule.Models.Recipe>("recipes", Recipes);
            writer.WriteIntValue("totalCount", TotalCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
