// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace WhojooSite.View.Clients.RecipesModule.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Recipe : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cookbookId property</summary>
        public long? CookbookId { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The ingredients property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::WhojooSite.View.Clients.RecipesModule.Models.Ingredient>? Ingredients { get; set; }
#nullable restore
#else
        public List<global::WhojooSite.View.Clients.RecipesModule.Models.Ingredient> Ingredients { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The ownerId property</summary>
        public Guid? OwnerId { get; set; }
        /// <summary>The spiceMixIngredients property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::WhojooSite.View.Clients.RecipesModule.Models.SpiceMixIngredient>? SpiceMixIngredients { get; set; }
#nullable restore
#else
        public List<global::WhojooSite.View.Clients.RecipesModule.Models.SpiceMixIngredient> SpiceMixIngredients { get; set; }
#endif
        /// <summary>The spices property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Spices { get; set; }
#nullable restore
#else
        public UntypedNode Spices { get; set; }
#endif
        /// <summary>The steps property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::WhojooSite.View.Clients.RecipesModule.Models.Step>? Steps { get; set; }
#nullable restore
#else
        public List<global::WhojooSite.View.Clients.RecipesModule.Models.Step> Steps { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::WhojooSite.View.Clients.RecipesModule.Models.Recipe"/> and sets the default values.
        /// </summary>
        public Recipe()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::WhojooSite.View.Clients.RecipesModule.Models.Recipe"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::WhojooSite.View.Clients.RecipesModule.Models.Recipe CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::WhojooSite.View.Clients.RecipesModule.Models.Recipe();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cookbookId", n => { CookbookId = n.GetLongValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "ingredients", n => { Ingredients = n.GetCollectionOfObjectValues<global::WhojooSite.View.Clients.RecipesModule.Models.Ingredient>(global::WhojooSite.View.Clients.RecipesModule.Models.Ingredient.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "ownerId", n => { OwnerId = n.GetGuidValue(); } },
                { "spiceMixIngredients", n => { SpiceMixIngredients = n.GetCollectionOfObjectValues<global::WhojooSite.View.Clients.RecipesModule.Models.SpiceMixIngredient>(global::WhojooSite.View.Clients.RecipesModule.Models.SpiceMixIngredient.CreateFromDiscriminatorValue)?.AsList(); } },
                { "spices", n => { Spices = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "steps", n => { Steps = n.GetCollectionOfObjectValues<global::WhojooSite.View.Clients.RecipesModule.Models.Step>(global::WhojooSite.View.Clients.RecipesModule.Models.Step.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("cookbookId", CookbookId);
            writer.WriteStringValue("description", Description);
            writer.WriteLongValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::WhojooSite.View.Clients.RecipesModule.Models.Ingredient>("ingredients", Ingredients);
            writer.WriteStringValue("name", Name);
            writer.WriteGuidValue("ownerId", OwnerId);
            writer.WriteCollectionOfObjectValues<global::WhojooSite.View.Clients.RecipesModule.Models.SpiceMixIngredient>("spiceMixIngredients", SpiceMixIngredients);
            writer.WriteObjectValue<UntypedNode>("spices", Spices);
            writer.WriteCollectionOfObjectValues<global::WhojooSite.View.Clients.RecipesModule.Models.Step>("steps", Steps);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
