// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using WhojooSite.View.Clients.RecipesModule.Models;
namespace WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Cookbooks
{
    /// <summary>
    /// Builds and executes requests for operations under \api\recipes-module\cookbooks
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CookbooksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Cookbooks.CookbooksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CookbooksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/recipes-module/cookbooks{?nextKey*,pageSize*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Cookbooks.CookbooksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CookbooksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/recipes-module/cookbooks{?nextKey*,pageSize*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::WhojooSite.View.Clients.RecipesModule.Models.ListCookbooksResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::WhojooSite.View.Clients.RecipesModule.Models.HttpValidationProblemDetails">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::WhojooSite.View.Clients.RecipesModule.Models.ListCookbooksResponse?> GetAsync(Action<RequestConfiguration<global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Cookbooks.CookbooksRequestBuilder.CookbooksRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::WhojooSite.View.Clients.RecipesModule.Models.ListCookbooksResponse> GetAsync(Action<RequestConfiguration<global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Cookbooks.CookbooksRequestBuilder.CookbooksRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::WhojooSite.View.Clients.RecipesModule.Models.HttpValidationProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::WhojooSite.View.Clients.RecipesModule.Models.ListCookbooksResponse>(requestInfo, global::WhojooSite.View.Clients.RecipesModule.Models.ListCookbooksResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::WhojooSite.View.Clients.RecipesModule.Models.HttpValidationProblemDetails">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PostAsync(global::WhojooSite.View.Clients.RecipesModule.Models.CreateCookbookRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PostAsync(global::WhojooSite.View.Clients.RecipesModule.Models.CreateCookbookRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::WhojooSite.View.Clients.RecipesModule.Models.HttpValidationProblemDetails.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Cookbooks.CookbooksRequestBuilder.CookbooksRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Cookbooks.CookbooksRequestBuilder.CookbooksRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::WhojooSite.View.Clients.RecipesModule.Models.CreateCookbookRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::WhojooSite.View.Clients.RecipesModule.Models.CreateCookbookRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Cookbooks.CookbooksRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Cookbooks.CookbooksRequestBuilder WithUrl(string rawUrl)
        {
            return new global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Cookbooks.CookbooksRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class CookbooksRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("nextKey")]
            public long? NextKey { get; set; }
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CookbooksRequestBuilderGetRequestConfiguration : RequestConfiguration<global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Cookbooks.CookbooksRequestBuilder.CookbooksRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CookbooksRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
