// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Recipes.Complete.Item;
using WhojooSite.View.Clients.RecipesModule.Models;
namespace WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Recipes.Complete
{
    /// <summary>
    /// Builds and executes requests for operations under \api\recipes-module\recipes\complete
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CompleteRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the WhojooSite.View.Clients.RecipesModule.api.recipesModule.recipes.complete.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Recipes.Complete.Item.WithRecipeItemRequestBuilder"/></returns>
        public global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Recipes.Complete.Item.WithRecipeItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("recipeId", position);
                return new global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Recipes.Complete.Item.WithRecipeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the WhojooSite.View.Clients.RecipesModule.api.recipesModule.recipes.complete.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Recipes.Complete.Item.WithRecipeItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Recipes.Complete.Item.WithRecipeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("recipeId", position);
                return new global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Recipes.Complete.Item.WithRecipeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Recipes.Complete.CompleteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CompleteRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/recipes-module/recipes/complete{?page*,pageSize*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Recipes.Complete.CompleteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CompleteRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/recipes-module/recipes/complete{?page*,pageSize*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::WhojooSite.View.Clients.RecipesModule.Models.ListCompleteRecipesResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::WhojooSite.View.Clients.RecipesModule.Models.ListCompleteRecipesResponse?> GetAsync(Action<RequestConfiguration<global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Recipes.Complete.CompleteRequestBuilder.CompleteRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::WhojooSite.View.Clients.RecipesModule.Models.ListCompleteRecipesResponse> GetAsync(Action<RequestConfiguration<global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Recipes.Complete.CompleteRequestBuilder.CompleteRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::WhojooSite.View.Clients.RecipesModule.Models.ListCompleteRecipesResponse>(requestInfo, global::WhojooSite.View.Clients.RecipesModule.Models.ListCompleteRecipesResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Recipes.Complete.CompleteRequestBuilder.CompleteRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Recipes.Complete.CompleteRequestBuilder.CompleteRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Recipes.Complete.CompleteRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Recipes.Complete.CompleteRequestBuilder WithUrl(string rawUrl)
        {
            return new global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Recipes.Complete.CompleteRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class CompleteRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("page")]
            public int? Page { get; set; }
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CompleteRequestBuilderGetRequestConfiguration : RequestConfiguration<global::WhojooSite.View.Clients.RecipesModule.Api.RecipesModule.Recipes.Complete.CompleteRequestBuilder.CompleteRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
