// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using WhojooSite.View.Clients.FuelModule.Api.FuelModule.TrackableObjects;
namespace WhojooSite.View.Clients.FuelModule.Api.FuelModule
{
    /// <summary>
    /// Builds and executes requests for operations under \api\fuel-module
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FuelModuleRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The trackableObjects property</summary>
        public global::WhojooSite.View.Clients.FuelModule.Api.FuelModule.TrackableObjects.TrackableObjectsRequestBuilder TrackableObjects
        {
            get => new global::WhojooSite.View.Clients.FuelModule.Api.FuelModule.TrackableObjects.TrackableObjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::WhojooSite.View.Clients.FuelModule.Api.FuelModule.FuelModuleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FuelModuleRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/fuel-module", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::WhojooSite.View.Clients.FuelModule.Api.FuelModule.FuelModuleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FuelModuleRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/fuel-module", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
